double a,b,c,d,s;
Console.Write("a: ");
a=Convert.ToInt32(Console.ReadLine());
Console.Write("b: ");
b=Convert.ToInt32(Console.ReadLine());
Console.Write("c: ");
c=Convert.ToInt32(Console.ReadLine());
Console.Write("d: ");
d=Convert.ToInt32(Console.ReadLine());
s=(a+b+c+d)/4;
Console.WriteLine(s);